### ISSUE TITLE
SearchClearIndex task

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-search-service#21]
In a fully consistent system, "clearing" an index shouldn't be required. Every change in the CMS is reflected in an incremental search update. And a full reindex will update every record the CMS knows about.

The problem is if you have removed records from the CMS through other means (e.g. restoring an older snapshot, or raw SQL). In this case, a reindex won't remove this index entry. 

I think we should allow easy clearing of a specific index, as a separate action from reindex. Bonus points for having a `clear=1` in the existing SearchReindex task though :D

**Comment by unclecheese** [comment]
Yeah, interesting. I'll see how many of these services allow an all-inclusive selection of documents (i.e. to get all the IDs first). Otherwise, we'll have to persist the search document ID to the dataobject, which feels a bit fragile. Also would raise questions about how to deal with non-dataobject documents.

Although I suppose "delete index", "create index" is more efficient.

**Comment by chillu** [comment]
> I'll see how many of these services allow an all-inclusive selection of documents 

All of them? It's a search engine ;) The problem is that you'd be querying every single record in order to get the document IDs. You can [limit search fields](https://www.elastic.co/guide/en/app-search/current/search-fields-weights.html) to just the identifier, but you'd still need to paginate through the whole data set. So at least in App Search, this won't be a cheap operation.

> Although I suppose "delete index", "create index" is more efficient.

"Clear index" isn't equivalent to "delete index" though. At least in App Search, there's configuration and analytics associated to an "engine" (they don't call it index I think). So unless you also take care to retain those and replicate it onto a new engine, you'd be causing data loss in App Search with this approach.

**Comment by unclecheese** [comment]
> All of them? It's a search engine

By "all-inclusive" I meant unpaginated for most purposes, e.g. getting 10,000 IDs in a 1MB payload or something.

In AppSeach, this will be a big problem. The maximum documents they'll give you per page is 100, and the maximum number of IDs in the deleteDocuments request is also 100. 

Would be fun to orchestrate with concurrency, as well, because ostensibly you'd have a query for a page of 100, and a subsequent delete for all those IDs. You'd then throw out several more requests for 100 on page 2, 3, etc. 

Seems like there could be a couple race conditions:
* A selection request returns IDs that no longer exist
* A deletion request is run for IDs that have already been deleted.

None of this is fatal, but it would severely handicap performance.

**Comment by madmatt** [comment]
This task has been re-written now. Previously there was a 'bug' where documents that were indexed but not properly removed from the index would get 'stuck' in engines, especially Elastic App Search as there's no way we can tell whether the deletion request was successful or not (the boolean true/false returned just means 'this has been queued for removal').

As part of https://github.com/silverstripe/silverstripe-search-service/pull/55, the ClearIndexJob now just loops over all documents, requests a batch of `max_batch_size`, removes them all, and continues until complete. This gets around lots of weird edge cases, and shared state between the CMS and the search engine index (previously, you'd often get complaints from the job because it didn't think it had finished).

Closing this issue as a result.
