### ISSUE TITLE
Allow custom field indexing

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-search-service#3]
As a Silverstripe CMS developer, I want a simple API for specifying what fields should be exposed by each content type so that I have full control over what goes into my search index.

## Acceptance Criteria

- [x] Any content type can index its declared search fields
- [x] Serialisation (e.g. field naming) is customisable
- [x] Data types are inferred by default, but can be overridden where applicable

**Comment by chillu** [comment]
Do we allow custom field names? Remember that those are exposed through frontend requests, so in some cases they might need to be shortened or sanitised. For example, `MicrosoftActiveDirectoryBackendIdentifier` might become `backendIdentifier` as a field name, because you don't want to expose the implementation detail of using active directory, or through which vendor.

It also means you can keep field names "stable" in the index when they change in DataObjects, so it decreases the coupling between the data layer (this module), and the presentation/logic layer (could be a `search-ui` implementation). 

If you agree with the feature, feel free to create a new card if you think this is scope creep here.

**Comment by chillu** [comment]
Note that App Search allows you to specify [results fields](https://swiftype.com/documentation/app-search/guides/result-settings) which might make the custom field naming overkill for security/obscurity purposes, but I think it's still a good idea to decouple them from DataObject naming.

**Comment by chillu** [comment]
Note that App Search allows you to specify [results fields](https://swiftype.com/documentation/app-search/guides/result-settings) which might make the custom field naming overkill for security/obscurity purposes, but I think it's still a good idea to decouple them from DataObject naming.

**Comment by chillu** [comment]
Tested this works. 

> Data types are inferred by default

There's no casting or type detection - I've created https://github.com/silverstripe/silverstripe-search-service/issues/24 for this as a more focused story.
